cluster = parcluster('Slurm');
RootPath = '/home/lecris/Projects/Floquet_Hamiltonian';
job3 = batch(cluster, 'TestInterface', ...
	'AdditionalPaths', "/home/lecris/has2667/lib", ...
	'AutoAddClientPath',false,...
	'AutoAttachFiles',false,...
	'Pool', 0);
wait(job3);
load(job3);
save('remoteTest.mat');